# 1、NDArray的使用

In [5]:
from mxnet import nd

x = nd.arange(12)
x


[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
<NDArray 12 @cpu(0)>

In [6]:
# 可以看出创建在 CPU 主内存上。其中“@cpu(0)”里的 0 没有特别的意义，并不代表特定的核。
x.shape

(12,)

In [7]:
x.reshape(3, 4) # 等价于x.reshape((-1, 4))或x.reshape((3, -1))


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [ ]:
nd.zeros()    # 注意内部还要加括号
nd.ones()
nd.array()
nd.random.normal(0, 1, shape=(3, 4))  # 每个元素都随机采样于均值为 0 标准差为 1 的正态分布。

In [8]:
x.exp()


[  1.00000000e+00   2.71828175e+00   7.38905621e+00   2.00855370e+01
   5.45981483e+01   1.48413162e+02   4.03428802e+02   1.09663318e+03
   2.98095801e+03   8.10308398e+03   2.20264648e+04   5.98741406e+04]
<NDArray 12 @cpu(0)>

In [ ]:
nd.dot(x, y.T)  # 矩阵计算（x和y的转置的矩阵乘法）

In [ ]:
nd.concat(x, y, dim=0)  行连接，即行增加了
nd.concat(x, y, dim=1)  列连接，即列增加了

In [ ]:
可以把y.exp()、x.sum()、x.norm()等分别改写为nd.exp(y)、nd.sum(x)、nd.norm(x)等。
以通过asscalar函数将结果变换为 Python 中的标量。
x.norm().asscalar()

In [13]:
y = nd.ones((3, 4))
y


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [15]:
y[1:3]   # y的1-2行数据


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 2x4 @cpu(0)>

In [16]:
y[2, 3] = 55   # 按下标访问数据
y


[[  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.  55.]]
<NDArray 3x4 @cpu(0)>

In [ ]:
Python 自带的id函数可以查看*变量内存地址*
z = y.zeros_like()
nd.elemwise_add(x, y, out=z)

In [17]:
id(y)

1705815944384

In [ ]:
可以通过array和asnumpy函数令数据在 NDArray 和 NumPy 格式之间相互变换。

# 2、数学基础

In [ ]:
向量、矩阵、点乘（内积）、叉乘、范数、特征向量和特征值。
范数：L1 范数是该向量元素绝对值的和；L2 范数是该向量元素平方和的平方根。
标量：可以理解为一个实数

# 导数和微分
导数规则：加减、乘、除、常数乘。
链式法则
泰勒展开
偏导数
梯度：一阶偏导数，即斜率
梯度 （数学名词）：梯度的本意是一个向量（矢量），表示某一函数在该点处的方向导数沿着该方向取得最大值，即函数在该点处沿着该方向（此梯度的方向）变化最快，变化率最大（为该梯度的模）。
黑塞矩阵：二阶偏导数
条件概率：P(A|B) = P(AB) / P(B)
期望：即平均值（概率*值的和不就是平均值???概率和肯定为1）

均匀分布：在区间ab取值概率相等。

In [18]:
# 练习(重点)   散度  旋度
求函数 f(x)=3*X_1^2+5*e^X_2 的梯度。
提示：梯度 = f(x)对x的偏导 = 利用链式法则

几个梯度方程演算：要把x转换成x的转置。

18.0

# 3、自动求梯度

In [19]:
from mxnet import autograd, nd

x = nd.arange(4).reshape((4, 1))
x


[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]]
<NDArray 4x1 @cpu(0)>

In [20]:
x.attach_grad() # 申请空间

In [21]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [22]:
y.backward()

In [23]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[  0.]
 [  4.]
 [  8.]
 [ 12.]]
<NDArray 4x1 @cpu(0)>

In [ ]:
# 小结
MXNet 提供autograd包来自动化求导过程。
MXNet 的autograd包可以对一般的命令式程序进行求导。
MXNet 的运行模式包括训练模式和预测模式。我们可以通过autograd.is_training()来判断运行模式。

这一章不是很懂。

# 4、python帮助

In [ ]:
dir函数
help函数
均匀分布、正态分布、泊松分布
mxnet.apache.org
