# 1、模块导入

In [1]:
import numpy as np  #导入模块
from sklearn import datasets  #用数据库去学习，或者把数据库放到tenserflow模块练习
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier   # 会选择邻近几个点作为他的邻居，综合临近几个点模拟出数据的预测值
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

# 2、导入数据集

In [8]:
iris = datasets.load_iris()  # 创建iris的数据，把属性存在X，类别标签存在y
#print(iris)
iris_x = iris.data
iris_y = iris.target
 
print(iris_x[:4,:])  # print出来iris的属性  每个sample四个属性，描述花的花瓣的长直径等
print(iris_y)        # 有三个类的花0，1，2

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# 3、分割数据集和测试集

In [9]:
# 把所有的data分成了要用来学习的data和用来测试的data   X_test和y_test测试的比例占了总数据的30%，随机种子默认为0，即每次划分都不一样
x_train,x_test,y_train,y_test = train_test_split(iris_x,iris_y,test_size = 0.3,random_state=0)  
print(y_train)        # 打乱了数据，尽可能的把数据打乱在学习过程中比不乱的更好

[2 2 0 2 1 2 1 2 0 0 1 1 1 2 0 0 1 2 2 2 1 1 1 1 2 1 2 2 0 1 2 1 0 1 0 0 0
 2 0 2 1 0 0 0 0 0 2 2 2 2 0 1 2 1 0 2 0 1 0 2 2 2 0 1 2 2 0 1 0 2 1 2 2 0
 2 2 0 1 2 0 0 1 1 1 1 0 1 1 2 1 0 0 0 1 0 2 1 1 0 0 2 2 0 1 1]


# 4、训练数据集并创建knn模型

In [11]:
knn = KNeighborsClassifier(n_neighbors=5) #定义用sklearn中的KNN分类算法
knn.fit(x_train,y_train)     # 用KNN进行数据集的学习，把创建的data放进去，他就自动帮你完成train的步骤

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

# 5、使用模型预测测试集

In [12]:
# 用我的model的属性去预测它是哪一种花
print(knn.predict(x_test))   #这里的knn就是已经train好了的knn

[1 1 1 0 2 0 1 1 2 1 1 1 1 0 0 2 0 2 0 0 0 0 0 0 2 1 1 0 2 1 2 2 2 2 0 2 0
 2 0 1 1 2 2 2 2]


# 6、评价模型

In [14]:
print(y_test)    # 对比真实值
print(knn.score(x_test,y_test))

[1 1 1 0 2 0 1 1 2 1 1 1 1 0 0 1 0 2 0 0 0 0 0 0 2 1 1 0 2 1 1 2 2 2 0 2 0
 2 0 1 1 2 2 2 2]
0.955555555556


# 7、调试参数

In [ ]:
1、修改算法模型
2、修改knn的k值
3、分类器中的其他参数修改
。。。

上面的方法都能使最后的评价得分改变。